dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
services:
  - postgresql
env:
  - postgres=postgres+psycopg2://postgres@localhost/postgres
# command to run tests
script:
  - pytest
